sudo: required

language: go

go:
  - 1.7.1

services:
  - docker

install:
  - go get github.com/gocraft/web

script:
  - docker run -v "$PWD":/go -w /go golang:1.7-alpine ./make.sh

after_success:
  - docker build -t jcombee/dmdd-agent:"$TRAVIS_TAG" .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push jcombee/dmdd-agent:"$TRAVIS_TAG"
